-- MySQL Script generated by MySQL Workbench
-- Fri May  5 10:14:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rungchuongvang
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rungchuongvang` ;

-- -----------------------------------------------------
-- Schema rungchuongvang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rungchuongvang` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rungchuongvang` ;

-- -----------------------------------------------------
-- Table `rungchuongvang`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rungchuongvang`.`room` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `status` INT NULL,
  `level` INT NULL,
  `owner` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rungchuongvang`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rungchuongvang`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `rank` INT NULL,
  `rank_score` INT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_room_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `rungchuongvang`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rungchuongvang`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rungchuongvang`.`question` (
  `id` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `topic` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rungchuongvang`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rungchuongvang`.`answer` (
  `id` INT NOT NULL,
  `content` VARCHAR(45) NULL,
  `result` BIT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_answer_question1_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `rungchuongvang`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rungchuongvang`.`room_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rungchuongvang`.`room_question` (
  `id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_room_question_room1_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_room_question_question1_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_question_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `rungchuongvang`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_room_question_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `rungchuongvang`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
